Improve find-python to add "Scripts" folder to PATH on Windows machines
actions/setup-python pull request #169
Opened 2020-12-16 12:13 UTC by nikita-bykov

In scope of this PR we added `Scripts` folder to PATH on Windows. Because starting from PyPy 7.3.1 this folder using for pip and anything that pip installs on Windows.

2020-12-16 17:19 UTC, konradpabjan approved these changes

2020-12-17 14:46 UTC, konradpabjan requested changes

2020-12-17 14:46 UTC, konradpabjan commented on src/find-python.ts
> +  }
Both blocks appear to be doing the same thing? This can just be simplified to
```
  // Starting from PyPy 7.3.1, the folder that is used for pip and anything that pip installs should be "Scripts" on Windows.
  if (IS_WINDOWS) {
    const scriptDir = path.join(installDir, 'Scripts');
    core.addPath(scriptDir);
  }
```

2020-12-17 14:51 UTC, dmitry-shibanov commented on src/find-python.ts
> +  }
Thank you. Removed duplicate block.

2020-12-17 14:57 UTC, konradpabjan approved these changes

2020-12-17 15:02 UTC, merged