Add support for adding a token on GHES to prevent rate limiting
actions/setup-python pull request #316
Opened 2022-01-10 12:37 UTC by HenrikPoulsen

**Description:**
Adding a new input to specify a token when running on GHES.
When running on GHES today `token` gets thrown away even when explicitly set to be a github.com token.
So there is no good way to avoid the rate limiting that would occur.

No idea if this change is idiomatic or not since I don't usually work with typescript. 
So let me know if there's any changes you would want me to make.

**Related issue:**
#229 

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-01-21 14:22 UTC, brcrista requested changes
We've discussed different approaches to this problem.  This approach should work, but requiring users to create a PAT in github.com to then use in GHES would create more problems than it would solve.

I think the best approach to unblock you is to fork the action on your GHES instance and apply these changes.

2022-01-21 15:21 UTC, HenrikPoulsen commented
What about fixing this for everyone that isn't me then?
Will something be done to fix this rate limiting issue? This PR at least proposes a generic workaround. Is it a hassle to set up? Sure
Does it solve a problem for people who are straight up blocked? Yes
Just making sure this isn't the end of the road for fixing this issue permanently

2022-01-24 09:38 UTC, lasse-aagren commented
The Solution implemented in this PR will continue to work exactly as today, for users not setting up til github.com PAT in their GHE project.

It will work until they hit a rate limit.

This PR provides a solution to that, for those interested. Isn't that to prefer compared to not have a solution?

2022-01-24 18:44 UTC, brcrista commented
It doesn't seem like a common issue so far, but we have thought about it.

Having to add a GHES-specific input to an action suggests to me that there's a smoother flow we should look for on the backend.  The solution we would like to implement is to make this flow part of [GitHub Connect](https://docs.github.com/en/enterprise-server@3.3/admin/configuration/configuring-github-connect/managing-github-connect).  That would solve the problem in a general way for all first-party actions and be consistent with other flows that fit this pattern.  No ETA on this, though.

2022-06-01 09:49 UTC, Vercasek1985 commented
Hello @brcrista
I am working in the automation team. We do the automation in ansible. Github is used heavily in our company (Kyndryl) and we really need this fix ASAP. Could you please help me, what can we do to prioritize this issue to be fixed in very near future?

2022-06-02 15:14 UTC, closed without merging