Add `build-npm` script
actions/setup-python pull request #329
Opened 2022-02-01 20:44 UTC by bexnoss

**Description:**
Adds a `build-npm` script and documents it. This basically implements the workaround from https://github.com/actions/setup-python/issues/38#issuecomment-634471245 with added declaration files as a npm script.

The `build-npm` script does the following things:
- `npm install` since in this use case the project is installed in node_modules it is necessary to install first
- `node -e "require('fs').rmSync('lib', { recursive: true, force: true })"` is `rm -rf lib` in Node. This is necessary because tsc thinks the generated declaration files in lib are source files and refuses to overwrite them.
- `tsc --declaration --declarationMap` builds the project with declarations into lib

**Related issue:**
https://github.com/actions/setup-python/issues/38

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-02-02 09:55 UTC, dmitry-shibanov commented
Hello @bexnoss. Thank you for your pull request. Can we use `npm ci` instead of `npm install` command ? As I know dependencies in package-lock.json will be updated through the npm install command and they won't be the same as for setup-python in `dist`.
Could you please rewrite `node -e \"require('fs').rmSync('lib', { recursive: true, force: true })\"` ? My main concern that the support for `rmSync` function was added in node 14, that is why it will fail on older versions.

2022-02-02 10:35 UTC, bexnoss commented
Hello @dmitry-shibanov, `npm install` is required in npm v7 to install dependencies from GitHub (see https://github.com/npm/cli/issues/2610) but since setup-python itself doesn't install any dependencies from GitHub it can be changed to `npm ci`.

I'll also change `rmSync` to `rmdirSync`.

2022-02-23 09:01 UTC, bexnoss commented
I have removed the documentation from the README and instead put it into the commit message. This way determined users can still find it but it isn't advertised as an intended use case.

The goals of this PR are to add a "correct" way of building @actions/setup-python as a NPM dependency so users don't have to experiment with various hacks and also to future proof this, so if the build process gets changed again the "build-npm" script can stay unchanged and keep working for this use case.

Please let me know if there is anything else that can be improved.

2022-02-25 07:24 UTC, dmitry-shibanov approved these changes

2022-04-11 10:18 UTC, dmitry-shibanov commented
Hello @bexnoss. Sorry for the late response. Could you please sync with the main branch ?

2022-04-12 11:15 UTC, marko-zivic-93 approved these changes

2022-04-12 12:24 UTC, dmitry-shibanov approved these changes

2022-04-12 14:47 UTC, brcrista requested changes
Thanks for the PR @bexnoss.  I don't think publishing as an NPM package is the direction we want to go in.  I'll comment on the issue, but I think composite actions is the right approach to reusability here.

2022-04-19 09:17 UTC, dmitry-shibanov commented
Hello everyone. For now I'm going to close the pull request because as mentioned the composite action should help.

2022-04-19 09:17 UTC, closed without merging