Cache on ghes
actions/setup-python pull request #363
Opened 2022-03-29 07:34 UTC by tiwarishub

**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-03-29 17:54 UTC, tiwarishub commented
Few CI checks are failing but I believe this is failing on master so I think it ok to ignore it?

2022-03-29 18:25 UTC, brcrista commented on src/utils.ts
> +      );
Since caching is just an optimization, I feel like a warning would be more appropriate here.

2022-03-29 18:26 UTC, brcrista requested changes
I think we should consider using warnings instead of errors for caching failures.

2022-03-29 18:50 UTC, tiwarishub commented on src/utils.ts
> +      );
we were already throwing an error in the case of GHES https://github.com/actions/setup-python/blob/main/src/setup-python.ts#L15. So i didn't change the end-user expectations. Should we change this behaviour?

2022-03-29 19:00 UTC, bishal-pdMSFT commented on src/utils.ts
> +      );
Agree, it will be a breaking behavior. In `actions/cache` action we do log a warning only. But here it was treated as an error earlier, may be because caching is additionally asked by user (by setting `cache` input) during nodejs setup.

2022-03-29 19:12 UTC, brcrista commented on src/utils.ts
> +      );
Ok, I can see this as an error since it's in line with the previous behavior.  In that case, just a small edit to the text:

```suggestion
      throw new Error(
        'Caching is only supported on GHES version >= 3.5.  If you are on a version >= 3.5, please check with your GHES admin if the Actions cache service is enabled or not.'
      );
```

Although, I'm confused here: can the Actions cache service be enabled/disabled independently?

2022-03-29 19:13 UTC, brcrista commented on src/utils.ts
> +      );
Despite the conversation on the case above, I think this still stands as a place where we should warn instead of fail.

2022-03-29 19:14 UTC, tiwarishub commented on src/utils.ts
> +      );
yeah as the user is explicitly asking for cache, will it make more sense to throw an error in case the cache service is not there.  I can see both pros and cons for throwing errors and warnings. I am not sure of the initial thought process behind throwing an error instead of a warning(i believe mostly because a user has asked explicitly for caching).  Please let me know your thoughts? I am open to both

2022-03-29 19:24 UTC, tiwarishub commented on src/utils.ts
> +      );
Make sense. I will update the PR

2022-03-29 19:58 UTC, tiwarishub commented on src/utils.ts
> +      );
Updated the PR

2022-03-30 06:42 UTC, bishal-pdMSFT approved these changes
LGTM

2022-03-30 07:49 UTC, dmitry-shibanov approved these changes

2022-03-30 10:19 UTC, vsafonkin commented on src/utils.ts
> +      );
Probably, it's not necessary to throw a error here?

2022-03-30 12:19 UTC, dmitry-shibanov commented on package.json
> +  "version": "2.2.3",
Could you please change it to the planning version of the setup-python action?

2022-03-30 12:32 UTC, tiwarishub commented on package.json
> +  "version": "2.2.3",
@dmitry-shibanov, Sorry I am not aware of the planned version. Could please share what is planned version.

2022-03-30 12:42 UTC, dmitry-shibanov commented on package.json
> +  "version": "2.2.3",
I think it should be 3.0.1 or 3.1.0 to be consistent with the setup-python action releases: https://github.com/actions/setup-python/releases/tag/v3.0.0

2022-03-30 12:43 UTC, tiwarishub commented on src/utils.ts
> +      );
As per the previous code, we were throwing an error in the GHES scenario https://github.com/actions/setup-python/blob/main/src/setup-python.ts#L15. Now we don't want to change end-user behaviour and this condition is similar to that that where workflow is running on GHES  and workflow has explicitly asked for the cache using ``cache`` option but it has not enabled the cache.  we had similar discussion here https://github.com/actions/setup-python/pull/363#discussion_r837782316

2022-03-30 12:47 UTC, tiwarishub commented on package.json
> +  "version": "2.2.3",
True, even I found this to be wired that package.json has 2.2.2 and released tag 3.0.0 which we generally keep the same.  So I thought this is already followed to keep them not in sync. Shall I fix this?

2022-03-30 18:47 UTC, brcrista commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
Is this message accurate?  It looks like `cache.isFeatureAvailable()` just looks for whether an environment variable is set.

https://github.com/actions/toolkit/blob/b4639928698a6bfe1c4bdae4b2bfdad1cb75016d/packages/cache/src/cache.ts#L53

2022-03-30 18:53 UTC, brcrista commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
If my understanding is correct, I would say something like

```suggestion
        'This runner is not configured to use the cache service.  Caching will be skipped.'
```

2022-03-30 18:53 UTC, tiwarishub commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
yes, this env var is only set when cache service is present otherwise this var will not be set. This else condition is for dotcom scenario so ideally this scenario should never occur because AC is always there in dotcom. But just to cover corner scenario i have added this

2022-03-30 19:09 UTC, brcrista commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
Ok I understand better now https://github.com/actions/runner/blob/408d6c579c36f0eb318acfdafdcbafc872696501/src/Runner.Worker/Handlers/NodeScriptActionHandler.cs

How about:

```suggestion
        'The runner was not able to contact the cache service.  Caching will be skipped.'
```

2022-03-30 19:11 UTC, tiwarishub commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
Okay. Let me update the PR with changes.

2022-03-30 19:20 UTC, tiwarishub commented on src/utils.ts
> +        'An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.'
done

2022-03-30 20:59 UTC, brcrista approved these changes

2022-03-30 21:58 UTC, vsafonkin approved these changes

2022-03-31 13:51 UTC, marko-zivic-93 approved these changes
All issues we noticed were referenced :) Everything seems ok now :)

2022-03-31 19:11 UTC, merged