feature: add `no-environment-update` input
actions/setup-python pull request #411
Opened 2022-05-26 14:20 UTC by mayeut

**Description:**
This option allows to specify if the action shall update environment variables (default) or not.
This allows to use the `setup-python` action in a composite action without side effect (except downloading/installing python if version is missing).

**Related issue:**
fix #410 

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

2022-05-26 14:56 UTC, mayeut commented
`e2e-cache / Test poetry (Python pypy-3.7-v7.x, windows-latest)` failure has nothing to do with this PR.

2022-05-26 14:59 UTC, brcrista requested changes
I'd like to explore other solutions besides adding complexity to the action.

Can you just add steps to the composite action?  For example:

```bash
# Save the environment
set > env.sh

# Restore the environment
source env.sh
```

2022-05-26 16:01 UTC, mayeut commented
@brcrista, 
there's no way to revert a `core.addPath` or a `core.exportVariable`

For exportVariable:
If they were already set, then the ones with exportVariable could be overriden back to their original values.
If they were not set, it's impossible to unset them: https://stackoverflow.com/questions/70137245/how-to-remove-an-environment-variable-on-github-actions

For addPath, it's values are always prepended to the "current" PATH, c.f. https://github.com/actions/toolkit/issues/655

2022-06-01 14:07 UTC, vsafonkin commented
Hi @mayeut, I have some concerns about this feature. In order to use python that is installed by action without $PATH updating you should use exact paths to the installed python in a composite action. If there are any other tools in composite action which use python implicitly, then these tools will not use the version you expect. This can lead to confusion about which python is used in which command or tool.

From my point of view an installation of python without adding to PATH may create more complications than solve problems.

2022-06-04 10:35 UTC, mayeut commented
> In order to use python that is installed by action without $PATH updating you should use exact paths to the installed python in a composite action. If there are any other tools in composite action which use python implicitly, then these tools will not use the version you expect. This can lead to confusion about which python version is used in some command or tool.
> From my point of view an installation of python without adding to PATH may create more complications than solve problems.

@vsafonkin,

This is an opt-in feature. It won't change a thing for existing users. If they choose to opt-in, they shall know the implications.
Furthermore, you can easily test your own action with a GHA workflow to check if it's working as expected or not but you can't possibly test how you'll break hundreds of downstream workflows using your action if you mess up the environment. I'd rather just get ahead of this most likely event by not messing with the environment in the first place.
Last time `setup-python` introduced a change in environment variables, it did create some issues (https://github.com/actions/setup-python/issues/159). I'd rather avoid that.

As said in an earlier comment, it's just impossible to restore the environment as it was before running `setup-python`. Even if it were, I feel that it would be better solved by adding a bit of complexity in this action, centralized, rather than incurring workarounds for downstream users.

2022-06-06 07:15 UTC, vsafonkin commented
@mayeut, ok, I see. Since the [AzDev `UsePython` task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops) has a similar input `addToPath` I think it makes sense to add this feature to the action.

2022-06-23 17:30 UTC, brcrista commented on action.yml
> +    default: false
```suggestion
  update-environment:
    description: 'Set this option if you want the action to update environment variables.'
    default: true
```

Putting boolean inputs in positive terms is usually easier for people to understand.

2022-06-23 19:48 UTC, mayeut commented on action.yml
> +    default: false
done

2022-06-24 09:27 UTC, dmitry-shibanov approved these changes

2022-06-24 09:32 UTC, marko-zivic-93 approved these changes

2022-06-24 09:34 UTC, IvanZosimov approved these changes

2022-06-29 14:14 UTC, vsafonkin approved these changes

2022-06-29 15:00 UTC, merged