Update CODEOWNERS
actions/setup-python pull request #573
Opened 2022-12-22 23:08 UTC by e-korolevskii

**Description:**
Describe your changes.

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-12-23 07:27 UTC, marko-zivic-93 approved these changes

2023-01-03 18:21 UTC, brcrista approved these changes

2023-01-04 09:05 UTC, dmitry-shibanov approved these changes

2023-01-04 14:49 UTC, brcrista commented on .github/CODEOWNERS
> +* @actions/runner-images-team
```suggestion
* @actions/setup-actions-team 
```

Should this be `setup-actions-team`?  I saw that used somewhere else.  Also, I think it's time to get rid of `actions-service` as codeowner.

2023-01-04 14:50 UTC, brcrista requested changes
Seems like https://github.com/actions/setup-python/pull/576 is the PR we want

2023-01-04 16:01 UTC, closed without merging