Add warning for python 2.7 on release/v1
actions/setup-python pull request #676
Opened 2023-05-23 14:12 UTC by dmitry-shibanov

**Description:**
In scope of this release we add warning for python 2.7 on release/v1.

**Related issue:**

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2023-05-23 17:30 UTC, MaksimZhukov approved these changes

2023-05-23 17:47 UTC, dsame approved these changes

2023-05-24 06:46 UTC, marko-zivic-93 approved these changes

2023-05-24 08:40 UTC, IvanZosimov approved these changes

2023-05-30 12:58 UTC, IvanZosimov requested changes

2023-05-30 12:58 UTC, IvanZosimov commented on src/setup-python.ts
> +    if (version.startsWith('2')) {
As the `setup-python@v1` doesn't use python-versions repo, I think this warning message isn't necessary.

2023-06-01 09:18 UTC, closed without merging